application: godfat2
version: 1
runtime: python
api_version: 1

handlers:
- url: /slides/.*
  script: slide.py

- url: /
  static_files: static/index.xhtml
  upload: static/index.xhtml

- url: /
  static_dir: static

# - url: .*
#   script: main.py
